### ISSUE TITLE
Postgres db connection error: wrong driver for the given database URL

### ISSUE THREAD

**Issue by AhmetTanakol** [liquibase/docker#11]
Hi,

I am trying to update my Postgresql database by executing the below command. The format of my URL looks like this in the logs `jdbc:postgresql://host:5432/dbname`. This should be a correct format. However, I keep getting this error `Connection could not be created to jdbc:postgresql://host:5432/dbname with driver org.postgresql.Driver.  Possibly the wrong driver for the given database URL`. Is there something wrong with the command I run?

Thank you

docker run --rm -v /backend/src/main/resources/db:/liquibase/changelog liquibase/liquibase --classpath=/liquibase/lib/postgresql.jar --url=${dbUrl} --changeLogFile=/liquibase/changelog/db-changelog.xml --username=${dbUsername} --password=${dbPassword} --contexts=${contexts} --logLevel=debug update

**Comment by PetarMI** [comment]
I am experiencing the same error when trying to run a container.

**Comment by AhmetTanakol** [comment]
@PetarMI You can try adding `--network host`

**Comment by r2liquibase** [comment]
Hi, @AhmetTanakol and @PetarMI ! Can you provide steps to replicate this issue? Thanks!

**Comment by Isuama** [comment]
Hi,
I am experiencing the same issue.
This is the command I executed.
```
docker run --rm -v //d/liqbase:/liquibase/changelog liquibase/liquibase --url="jdbc:postgresql://<ip>/<db>?curr
entSchema=<schema>" --changeLogFile=/liquibase/changelog/testChangeLog.xml --username=<usr> --password=<pwd> generateChangeLog
```
error:
```
Liquibase Community 3.10.0 by Datical
Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not b
e created to jdbc:postgresql://192.168.137.1:5432/my-docker?currentSchema=public with driver org.postgresql.Driver.  Possibly the wrong
driver for the given database URL
For more information, please use the --logLevel flag
```
I have already connected to DB with PgAdmin tool.

**Comment by r2liquibase** [comment]
Hi, @Isuama ! What can you tell me about your PostgreSQL database? Where and how is it hosted? Thanks!

**Comment by Isuama** [comment]
Wooh....Isn't is working for dockerized Postgres. It works fine with the Postgres which is hosted directly on server.

**Comment by r2liquibase** [comment]
Can you issue `docker inspect <container>` and verify that you have the right IP address? Sorry to ask a silly question like that but it's tripped me up in the past. Or, if you prefer to connect the host and NAT to the container, then use `-p 5432:5432`.

Let me know what you find.

**Comment by Isuama** [comment]
This was the command I used to up the Postgres.
```docker run --name isuru-pg -e POSTGRES_PASSWORD=postgres -p 5432:5432 -p 8080:8080 -d postgres:13```

Since it is exposed to outside, it should be available as both hostip and containerip. Isn't it.
I tried both ways. May be I am doing something silly here.

**Comment by r2liquibase** [comment]
Given that you're passing in the `postgres` password, can you reply with your Docker command to run Liquibase? I'm not sure your URL is correctly format as it is missing a port.

Here's what you put in above: 
```docker run --rm -v //d/liqbase:/liquibase/changelog liquibase/liquibase --url="jdbc:postgresql://<ip>/<db>?curr
entSchema=<schema>" --changeLogFile=/liquibase/changelog/testChangeLog.xml --username=<usr> --password=<pwd> generateChangeLog```

Also, I'm concerned about the spelling of your liquibase folder on the D drive.

To sum up, please provide, start to finish, the steps you follow to see the problem. And, your changelog. 

Thanks!

Robert

**Comment by Isuama** [comment]
Seriously I'm not sure what was the issue. Could be some sort of a network issue. After resetting my local IP it seems fine now. spelling was correct about the D driver as it is how we usually point when it is on Windows.

**command for postgres**
```docker run --name isuru-pg -e POSTGRES_PASSWORD=postgres -p 5432:5432 -p 8080:8080 -d postgres:13```

**command for liquibase**
```docker run --rm -v //d/liqbase:/liquibase/changelog liquibase/liquibase --url="jdbc:postgresql://<host ip>:5432/test?currentSchema=public" --changeLogFile=/liquibase/changelog/testChangeLog.xml --username="postgres" --password="postgres" generateChangeLog ```

**Comment by szandany** [comment]
This great, Isuama!  I was about to reply with more suggestions, but it looks like your issue is resolved.

**Comment by r2liquibase** [comment]
Wonderful, @Isuama ! Let us know how we can help in the future!!!

**Comment by AhmetTanakol** [comment]
In my case I was running the container inside a kubernetes pod. Using the network of the host worked for me. Is it possible to give more details about the connection errors?
