### ISSUE TITLE
Using path name starting with "./" creates double paths using the includeAll tag

### ISSUE THREAD

**Issue by szandany** [liquibase/docker#123]
STR
Create a master changelog with the includeAll tag referencing a subfolder with a path starting with "./"

For example:
`<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.1.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">
    <includeAll path="./sql" relativeToChangelogFile="true"/>
</databaseChangeLog>` 

Run: `liquibase status`
`$ docker run --rm -v /Users/support.liquibase.net/CLI-Projects/MSSQL_Jenkins/DEV/changeLogs/:/liquibase/changelog liquibase/liquibase:latest --url="jdbc:sqlserver://hostname;database=DEV;" --changeLogFile=changelog/changeLog.xml --username=sa --password=password status --verbose
...
Starting Liquibase at 12:25:53 (version 4.4.2 #39 built at 2021-07-22 18:11+0000)
Liquibase Version: 4.4.2
Liquibase Community 4.4.2 by Datical
18 change sets have not been applied to sa@jdbc:sqlserver://host:port#;maxResultBuffer=-1;sendTemporalDataTypesAsStringForBulkCopy=true;delayLoadingLobs=true;useFmtOnly=false;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=DEV;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;
     changelog/./sql/changeLog.sql::createTable_salesTableZ::SteveZ
     changelog/./sql/changeLog.sql::insertInto_salesTableZ::SteveZ
     changelog/./sql/changeLog.sql::createTable_CustomerInfo::SteveZ
     changelog/./sql/changeLog.sql::addPrimaryKey_pk_CustomerTypeID::Martha
     changelog/./sql/changeLog.sql::CustomerInfo_ADD_address::Amy
     changelog/./sql/changeLog.sql::CREATE_PROCEDURE_[dbo].[CustOrderHist1]::Mike
     changelog/./sql/changeLog.sql::CREATE_PROCEDURE_[dbo].[CustOrderHist2]::Mike
     changelog/./sql/changeLog.sql::ALTER_PROCEDURE_[dbo].[CustOrderHist2]::Kevin
     changelog/./sql/changeLog.sql::createTable_salesTableZ2::SteveZ
     changelog/sql/changeLog.sql::createTable_salesTableZ::SteveZ
     changelog/sql/changeLog.sql::insertInto_salesTableZ::SteveZ
     changelog/sql/changeLog.sql::createTable_CustomerInfo::SteveZ
     changelog/sql/changeLog.sql::addPrimaryKey_pk_CustomerTypeID::Martha
     changelog/sql/changeLog.sql::CustomerInfo_ADD_address::Amy
     changelog/sql/changeLog.sql::CREATE_PROCEDURE_[dbo].[CustOrderHist1]::Mike
     changelog/sql/changeLog.sql::CREATE_PROCEDURE_[dbo].[CustOrderHist2]::Mike
     changelog/sql/changeLog.sql::ALTER_PROCEDURE_[dbo].[CustOrderHist2]::Kevin
     changelog/sql/changeLog.sql::createTable_salesTableZ2::SteveZ
Liquibase command 'status' was executed successfully.`

Notice that Liquibase generate double entries for each changeset.

**Comment by jandroav** [comment]
This bug is fixed:
![image](https://user-images.githubusercontent.com/67458478/236831618-f16051b8-4049-468a-9fa3-cb58eba34417.png)
