### ISSUE TITLE
Install AWS SSM Agent

### ISSUE THREAD

**Issue by r2liquibase** [liquibase/docker#127]
To use the container in AWS CodeBuild, we need to install and configure the AWS SSM agent.

https://docs.aws.amazon.com/codebuild/latest/userguide/session-manager.html
https://aws.amazon.com/premiumsupport/knowledge-center/install-ssm-agent-ec2-linux/

The deadline is October 18, 2021.

**Comment by nvoxland** [comment]
We should be keeping the base image as lightweight as possible. People can use the FROM liquibase/liquibase directive in a new file and add it there.
