### ISSUE TITLE
bash not found

### ISSUE THREAD

**Issue by xenoterracide** [liquibase/docker#13]
```
docker run -v $PWD/src/main/resources/db/changelog:/liquibase/changelog \
  --network service-db-main-migration_net \
  liquibase/liquibase:3.10.x \
  --changeLogFile /liquibase/changelog/db.changelog-master.xml \
  --url=jdbc:postgresql://nuvola.db:5432/briggo_production \
  --logLevel=info \
  --contexts=test \
  --driver=org.postgresql.Driver \
  --username=postgres \
  --password=DontUseThisPassword \
  update || ( docker-compose -f docker/github/docker-compose.yml logs && exit 1)
  shell: /bin/bash -e {0}
7b59e5bff284: Download complete
2d74cee1d142: Verifying Checksum
2d74cee1d142: Download complete
80a8dd427fd7: Verifying Checksum
80a8dd427fd7: Download complete
1da8cfc7fd0c: Verifying Checksum
1da8cfc7fd0c: Download complete
b6abafe80f63: Pull complete
f235467ca4dd: Pull complete
80bfc14f7149: Pull complete
86df353038e8: Pull complete
45d35ea0921b: Pull complete
999fa03fc7c0: Pull complete
4063048b32f7: Pull complete
d0c77342a5b1: Pull complete
fb1414450605: Pull complete
9d1de4ce3c3a: Pull complete
285ac78f3f78: Pull complete
9ac934dc6b12: Pull complete
2d74cee1d142: Pull complete
7dab49f9930f: Pull complete
7b59e5bff284: Pull complete
80a8dd427fd7: Pull complete
1da8cfc7fd0c: Pull complete
Digest: sha256:084ac35ad21c7ed860c48d94fe50d3b71caab90675935f09bec3b0d02124e4fa
Status: Downloaded newer image for liquibase/liquibase:3.10.x
env: can't execute 'bash': No such file or directory
.FileNotFoundError: [Errno 2] No such file or directory: './docker/github/docker-compose.yml' # this piece is actually an error in my script, but the can't execute bash is coming from trying to run bash in alpine
##[error]Process completed with exit code 1
```

note this changed with the release today

**Comment by treyhendon** [comment]
We have a similar problem after the recent update.  Our Docker file is using Yum to install PSQL Client and Yum is missing.  Going from `openjdk:13` to `openjdk:8-jre-alpine` seems to be cause.

**Comment by dhwanitsshah** [comment]
Getting the same issue with latest tag (liquibase/liquibase:latest)

Pulling liquibase (liquibase/liquibase:latest)...
latest: Pulling from liquibase/liquibase
e7c96db7181b: Pull complete
f910a506b6cb: Pull complete
b6abafe80f63: Pull complete
c02afe786c8e: Pull complete
1f3aa36a9e26: Pull complete
277362622ff1: Pull complete
81c42c273fae: Pull complete
bbdb8af6a2a3: Pull complete
6a7208a213d0: Pull complete
9b1bb7c7de7e: Pull complete
71dfc42c0db3: Pull complete
1e842f32e7d0: Pull complete
735cc0955fa0: Pull complete
7e97f11e6c91: Pull complete
b0b30590f6a3: Pull complete
ec699d7636e3: Pull complete
bca609438280: Pull complete
d144ed163252: Pull complete
ad5b0e2f94a8: Pull complete
Digest: sha256:4387f2f155c2c976e5de44718095cd298b2887143cc06d47bd7b9749a7ace88e
Status: Downloaded newer image for liquibase/liquibase:latest
env: can't execute 'bash': No such file or directory
make: *** [liquibase-migrate] Error 127

**Comment by dhwanitsshah** [comment]
I have given a fix in https://github.com/liquibase/docker/pull/15, hope that gets accepted!

**Comment by devopsix** [comment]
Same issue here.

Liquibase, please consider [rethinking your image tagging strategy](https://github.com/liquibase/docker/issues/3#issuecomment-661877375). For cases like this, there should be a tag that can be used to pin to a particular version.

**Comment by devopsix** [comment]
Maybe this workaround is of some help for anyone who cannot wait for a fix (inspired by the change proposed by @dhwanitsshah):

```
FROM liquibase/liquibase:3.10.x

# Workaround for https://github.com/liquibase/docker/issues/13
USER root
RUN apk add --update --no-cache bash gnupg
USER liquibase
```

**Comment by konstantinblaesi** [comment]
For anyone using ms sql or azure sql databases, that support is broken as well for me see #17

**Comment by xenoterracide** [comment]
my workaround was to use the previous sha

`liquibase/liquibase@sha256:c350af8d22674cf9c14f6ec29217f107bc2ba33d094cae64d367affdb56639e0`

**Comment by killnine** [comment]
Same issue here, ugh. 

Last few image updates have broken our builds.

**Comment by treyhendon** [comment]
We shifted over to using root and run apk as well.

From what I understand the change in `openjdk` is due to licensing.  I completely understand that.  Hopefully this will be the last major breaking change for a while.

**Comment by xenoterracide** [comment]
I agree with @devopsix but not so much the particular version (though I agree with that too) but this should have been a tag with -alpine. But even said... it appears this image just doesn't work... so what else is needed is testing of the image before tagging.

**Comment by marcoblos** [comment]
Thanks for the tip @xenoterracide. Since they started introducing the version 4, last week, started to break my pipelines also, and now with the digest code, I hope it becomes immutable 😹

**Comment by r2liquibase** [comment]
Hi! Going forward, we will definitely use branches and make tagging additive. We will not remove tags.

**Comment by r2liquibase** [comment]
We've reached a point of stability with the images. Our apologies for the screwup.

Can you verify that things are working as expected now? Thanks!

**Comment by r2liquibase** [comment]
I think we've got this sorted. Just waiting on the hub.docker.com build queue.

**Comment by r2liquibase** [comment]
Ok, team, thanks a ton for your patience and thoughts. We've got a successful release to latest.
