### ISSUE TITLE
Tags deleted from DockerHub

### ISSUE THREAD

**Issue by resnikb** [liquibase/docker#14]
Hello,

Today our pipelines started breaking as image tags that they depend on have been deleted from DockerHub.
Would it be possible for you to restore them? 

Unfortunately, DockerHub doesn't seem to enforce tag immutability and allows deletion as well, but it would be really great if you could change your deployment process so it keeps existing tags. Otherwise, any kind of dependency on liquibase images becomes nearly impossible to manage.

Cheers,
Bojan

**Comment by r2liquibase** [comment]
Hi, @resnikb ! What were the tags you relied on? Thanks!

**Comment by r2liquibase** [comment]
Let me know which tags need to be recreated. This will not happen again. Thank you!
