### ISSUE TITLE
Is there a plan to make Liquibase an official tagged image on Dockerhub?

### ISSUE THREAD

**Issue by romeelk** [liquibase/docker#142]
What is the roadmap for making the docker image an official image?
https://hub.docker.com/r/liquibase/liquibase
https://docs.docker.com/docker-hub/official_images/

Having It official would help in organisations that require the official tag because of software compliance reasons?

**Comment by molivasdat** [comment]
@romeelk There is not a current plan to make liquibase an official docker image built by docker.

**Comment by StevenMassaro** [comment]
https://github.com/docker-library/official-images/pull/8409

**Comment by jnewton03** [comment]
fixed in https://github.com/docker-library/official-images/pull/8409 but waiting on docker to approve

**Comment by jnewton03** [comment]
docker has merged liquibase into its official images here:
https://github.com/docker-library/official-images/pull/8409
https://github.com/docker-library/docs/pull/1803

Now just waiting on the checkmark to show up in docker hub 🎉
