### ISSUE TITLE
Push image to ECR Public Gallery?

### ISSUE THREAD

**Issue by emersonf** [liquibase/docker#145]
Would you be up for pushing the image to the [ECR Public Gallery](https://gallery.ecr.aws/), in addition to pushing it to Docker Hub? ECR Public Gallery is an appealing public registry to clients who run workloads on AWS; lower latency, fast transfers, and no registration or rate limits to deal with, etc. 

It should be free, [unless you'd send more than 5TB/mo outside AWS](https://aws.amazon.com/ecr/pricing/).

**Comment by jnewton03** [comment]
@emersonf @Constantin07 this is now verified in AWS ECR:
https://gallery.ecr.aws/liquibase/liquibase
