### ISSUE TITLE
Include drivers for all supported databases

### ISSUE THREAD

**Issue by adeelmalik78** [liquibase/docker#157]
Received customer feedback: I expected mysql driver to be packaged inside docker image just like postgres driver. Customer ended up running 

`docker run -it liquibase/liquibase sh -c "lpm add mysql && liquibase update "`

Suggest including drivers and extensions for all Liquibase supported databases. This means include drivers for these platforms:

* Oracle
* SQL Server
* Postgres
* MySQL
* MariaDB
* Snowflake
* Cassandra
* MongoDB
* Redshift
* CockroachDB
* Cloud Spanner
* CosmosDB
* DB2
* Firebird
* SQLite
* Apache Derby
* H2
* Sybae
* Informix
* HyperSQL
* Teradata
* VoltDB
* Vertica
* Impala
* SAP Hana
* SAP MaxDB
* Hive
* Yugabyte
* Neo4j

**Comment by jnewton03** [comment]
we have workarounds and examples for these use cases.  We also have LPM as an option to install drivers.  We do not want to pre-package all drivers as that will make the image way too large.
