### ISSUE TITLE
Is it possible to not update that direct tags themselves but simply add new ones?

### ISSUE THREAD

**Issue by barucoh** [liquibase/docker#16]
Yesterday after the update to `liquibase/liquibase:latest` some of my pipelines broke so I had to hard code using the `3.10.x` version.
Today you updated the `3.10.x` version which broke my pipelines as well...

Is it possible to not update a specific tag but rather with every update just add a new tag?

**Comment by r2liquibase** [comment]
Absolutely. That's the plan moving forward. My apologies for the hassle. Won't happen again.
