### ISSUE TITLE
Unknown column DATETIME_PRECISION 

### ISSUE THREAD

**Issue by emanuelbesliu** [liquibase/docker#160]
I'm using MemSQL Docker image and trying to integrate Liquibase. I'm able to execute `status`, `update` and `updateSQL`. After executing UpdateSQL, the table `DATABASECHANGELOG` is created. When the table is on every execution gives me this error:

`Unknown column 'DATETIME_PRECISION' in 'field list'`

**Comment by jnewton03** [comment]
closing as stale
