### ISSUE TITLE
Add a slim/alpine variant

### ISSUE THREAD

**Issue by jnewton03** [liquibase/docker#171]
The current full version image is nearing 400MB.  It would be really nice to have a `-alpine` or `-slim` type variant for the instances where smaller images are preferred.  It is expected than alpine variant would not be straightforward to extend.  It would be for barebones basic liquibase operations.

Examples:

https://hub.docker.com/_/eclipse-temurin
https://hub.docker.com/_/postgres

**Comment by acasciani** [comment]
+1

**Comment by N4SoftwareNinja** [comment]
+1
an alpine version would be really nice. not only for image size reasons, but also because ubuntu has such a huge amount of known security issues so that using this image gives a bad feeling

**Comment by jnewton03** [comment]
re-opening issue.  While the dockerfile.slim is available, the release process is currently not working @jandroav

**Comment by jandroav** [comment]
Fixed in #217 and #214

**Comment by N4SoftwareNinja** [comment]
Nice to see this being completed. Is there already a timeline when the first release of the slim variant will be available?

**Comment by jnewton03** [comment]
Hi @N4SoftwareNinja (and anyone else interested in the alpine image).  It's been released starting with `4.21`.  You can find the tags here:
https://hub.docker.com/r/liquibase/liquibase/tags
