### ISSUE TITLE
STOP UPDATING BASE IMAGE FOR PUBLISHED TAGS!

### ISSUE THREAD

**Issue by quozd** [liquibase/docker#18]
Sorry for the caps lock, but this is ridiculous. 2 base image changes since yesterday. How can we rely on that?
If you're struggling to set up an immutable tags workflow, just let us know. We're happy to help.

**Comment by r2liquibase** [comment]
You're right. The previous version needed a lot of help as we're attempting to publish an Official Image. 

https://github.com/docker-library/official-images/pull/8409

**Comment by r2liquibase** [comment]
We're meeting today to make sure we're using tags correctly. Please reopen if you continue to have issues.

**Comment by jack-r-warren** [comment]
Another breaking change to the image [happened two days ago](https://hub.docker.com/r/liquibase/liquibase/tags), _[undoing the breaking change](https://github.com/liquibase/docker/commit/bb3bd7ce5258ffc19ba7ec1656d2edb93b767b2a) brought up in #24_. This once again broke our deployment after we compensated for the last change.

We'd really like a tag that we can rely on--we appreciate the development on this but it would be super helpful to have a tag that's a bit more stable.
