### ISSUE TITLE
can not execute `lpm` when using arm image

### ISSUE THREAD

**Issue by asdfsx** [liquibase/docker#194]
I'm trying to execute `lpm` to install mysql driver into arm version docker image. But I got the following error
```
bash: /usr/local/bin/lpm: cannot execute binary file: Exec format error
```
I think the problem is that you pack wrong version into the image. So I download arm version `lpm` from [liquibase-package-manager](https://github.com/liquibase/liquibase-package-manager/releases), put it into the image and replace the older one, and the problem solved.

**Comment by jnewton03** [comment]
hi @asdfsx !  I believe you are correct and this was likely introduced when we started building images for both intel and arm64 architectures here: https://github.com/liquibase/docker/pull/184

Would you be interested in opening a PR to help fix it?

CC @nvoxland @filipelautert @mcred

**Comment by filipelautert** [comment]
Hey @jnewton03 I created PR https://github.com/liquibase/docker/pull/198 that may fix it.

**Comment by networkhermit** [comment]
@jnewton03 @mcred Is it possible to create a new release to fix the `lpm` arm64 issue?

**Comment by filipelautert** [comment]
Hello @networkhermit - if all goes well Liquibase 4.22.0 will be released sometime next week.
