### ISSUE TITLE
Ability to use extensions without creating a new image

### ISSUE THREAD

**Issue by nvoxland** [liquibase/docker#213]
## Description

To use extensions (and drivers), the jars have to be in the java classpath when liquibase first starts, and the only place it ever looks is internal/lib, lib, and ./liquibase_libs regardless of what the "classpath" setting is.

#206 attempted to fix this by add a specific mount point for lib to make it more obvious that they go there and updated the readme to use that mount point. It also replaces other uses of the deprecated "classpath" setting in favor of "searchPath" in the docs.

However, it broke people creating sub-images that add things to `lib` and was reverted.

**Comment by nvoxland** [comment]
For the original PR, I thought about changing workspace in Dockerfile to be /liquibase/changelog which would allow users to have a liquibase_libs subdirectory in their project directory which gets mounted to /liquibase/changelog and then those "local" jars would be used as well. I ended up not changing that, since I though that might be a breaking change if people are setting their searchPath relative to the /liquibase workspace it currently has.

But, I left the change in docker-entrypoint.sh that makes liquibase have an absolute path, so users can at least override the working directory if they want and everything will still work for them.

Maybe that ends up being less of a potentially-breaking change for users though? 

Or maybe we need a different approach completely?

**Comment by filipelautert** [comment]
@nvoxland And what about liquibase-package-manager? I remember some discussions about using it to install drivers and other dependencies for liquibase, so maybe it would be better to facilitate the use of lpm (like passing an environment variable with the packages to install or make it easy to extend the image and call it) so people can use it to install what they require?

**Comment by jandroav** [comment]
@filipelautert I like it. It is almost the same way Jenkins does it

```
FROM jenkins/jenkins:lts-jdk11
COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
```

More info here: https://github.com/jenkinsci/docker

@jnewton03 what do you think?

**Comment by jnewton03** [comment]
Maybe I'm misunderstanding the question, @jandroav / @filipelautert .  We already install LPM:
https://github.com/liquibase/docker/blob/main/Dockerfile#L22-L29

And we have examples of using LPM to extend the Dockerfile:
https://github.com/liquibase/docker#new-container-example

**Comment by filipelautert** [comment]
So I think we have lpm and people can extend the image and copy whatever they need to the lib directory. For me it seems enough @jandroav , unless we have any other users requests about it.  What do you guys think?

**Comment by jnewton03** [comment]
I agree @filipelautert .  @nvoxland what say you?

**Comment by jnewton03** [comment]
Closing issue since we have solutions available today.  Feel free to re-open if issues persist.
