### ISSUE TITLE
rm -rf /var/lib/apt/lists/* 

### ISSUE THREAD

**Issue by VadymShkarbul** [liquibase/docker#216]
And in general, who does this: `rm -rf /var/lib/apt/lists/*`
Were you threatened?

**Comment by jnewton03** [comment]
hi @VadymShkarbul , can you clarify on the issue you're reporting?  If you're referring to the Dockerfile, we tried to construct the image according to Docker Best Practices:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by VadymShkarbul** [comment]
The authors of Docker best practices will give you a standing ovation, but BigQuery users will not.
First, you remove the contents of the /var/lib/apt/lists directory, which is important for package management in Ubuntu, and then you permanently disable the ability to use root, leaving neither the ability to use archivers nor to install them. Which makes it extremely difficult to install BigQuery JDBC drivers using this image.

**Comment by mcred** [comment]
There is a [package manager](https://github.com/liquibase/liquibase-package-manager) in the docker container to help install liquibase things. This includes the `liquibase-bigquery` extension. Feel free to open an issue or PR with the package manager to add BigQuery JDBC drivers there. Then you could install those drivers without the `/var/lib/apt/lists` directory or the root user.

**Comment by jnewton03** [comment]
Hi @VadymShkarbul , as @mcred mentioned above LPM is the preferred solution for your particular use-case.  Other options would be loading the bigquery driver via [mount](https://github.com/liquibase/docker#driver-and-extensions-example) or extending the dockerfile.  Examples of extending the dockerfile for custom usage is located [here](https://github.com/liquibase/docker/tree/main/examples).

Do these options resolve your issue?
