### ISSUE TITLE
Liquibase 4.22.0 avalaible but not the docker image 

### ISSUE THREAD

**Issue by sebastienrospars** [liquibase/docker#220]
Hi, 

Do you have some information about the availability of the docker image with liquibase 4.22.x ? 

Thanks by advance :)

**Comment by jnewton03** [comment]
hi @sebastienrospars!  We had to pull back the 4.22 release.  More details here:
https://github.com/liquibase/liquibase/releases/tag/v4.22.0

**Comment by sebastienrospars** [comment]
Oh okay, thanks for the link :)
