### ISSUE TITLE
`update` failed using the latest liquibase image

### ISSUE THREAD

**Issue by rexwangcc** [liquibase/docker#24]
Hi! When we tried to run `docker run --rm liquibase/liquibase update` today with the latest docker image, the following error poped up:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"update\": executable file not found in $PATH": unknown.
```

This never happened before with previous images, but since the previous docker tags on DockerHub were deleted, there's no way for us to go back and pin to an older version ... Could you consider updating your workflow to not delete existing docker tags but rather append new tags to the list?

**Comment by bsuchorowski** [comment]
This is because entrypoint of dockerfile has changed into cmd (see https://github.com/liquibase/docker/commit/a7137cb624c3a42e85ee4fc8280428cb4a65707d#diff-3254677a7917c6c01f55212f86c57fbf)

Therefore you need to add "/liquibase/liquibase" to your command:
```docker run --rm liquibase/liquibase /liquibase/liquibase update```

**Comment by rexwangcc** [comment]
Thanks! `docker run --rm liquibase/liquibase /liquibase/liquibase update` worked for me.
