### ISSUE TITLE
Rebuild of Dockerfile?

### ISSUE THREAD

**Issue by mtcolman** [liquibase/docker#254]
Hi, from Dockerhub I can see last release of liquibase image was a month ago:
![image](https://github.com/liquibase/docker/assets/33348891/ad2de4e9-ebae-40de-87db-42b0c65a0ba5)

And I can see from the [liquibase dockerfile](https://github.com/liquibase/docker/blob/main/Dockerfile) that the base image is `FROM eclipse-temurin:17-jre-jammy as production`.

From Dockerhub I can see the latest release of `eclipse-temurin:1-jre-jammy` has been last pushed 6 days ago, which means the liquibase image cannot be using it (the latest version of base image):
![image](https://github.com/liquibase/docker/assets/33348891/a43a6717-f0e7-45ed-9ae3-4314a5ae85ed)

Is there a process for the liquibase image to be updated and pushed using the latest version of `eclipse-temurin:17-jre-jammy` ahead of a new liquibase application release? And can anything be implemented to ensure liquibase keeps up with updates to the underlying base image? We are scanning the liquibase docker image and encountering vulnerabilities we need to fix, which are resolved in the latest push of `eclipse-temurin:1-jre-jammy`.

Thanks, Matt

**Comment by jnewton03** [comment]
hi @mtcolman , we rebuild the image anytime there is a new version of liquibase so that we maintain immutable tags.  We just released liquibase 4.25.0 which should have rebuilt the Dockerfile as well.  Can you confirm if you're still seeing those vulnerabilities?
