### ISSUE TITLE
diff command does not produce any changelog file

### ISSUE THREAD

**Issue by Isuama** [liquibase/docker#27]
I used "**diff**" command to generate changelog file by comparing two databases(Postgres and Oracle). Though command executed successfully it does not  produce any changelog file.
**Command**
```
docker run --rm -v //d/liqbase:/changelogs <image> --changeLogFile=diffChangeLog.xml --outputFile=mydiff.txt --url="jdb
c:postgresql://<postgres ip>:5432/<db name>?currentSchema=public" --username="<usr>" --password="<pwd>" --referenceU
rl="jdbc:oracle:thin:@<oracle ip>:1521/<SID>" --referenceUsername="<db name>" --referencePassword="<pwd>" diff
```
**Result**
```
Liquibase Community 3.10.0 by Datical
Diff Results:
Liquibase command 'diff' was executed successfully.
```

**Comment by r2liquibase** [comment]
It looks like the diff output was put on containers home directory. How about using --outputFile=/changelogs/mydiff.txt? That should persist to d:/liqbase. Let me know how that works.

**Comment by Isuama** [comment]
yes. But why can't I get the changelog. I did the same change to the changelog param as, --changeLogFile=/changelogs/diffChangeLog.xml but it doesn't generate any.

**Comment by Isuama** [comment]
I think I have misunderstood some commands there. by using the command **"diffChangeLog"** I could generate the changelog.xml file.
