### ISSUE TITLE
Adding tags to the docker images

### ISSUE THREAD

**Issue by metalshanked** [liquibase/docker#3]
Hi,
Is it possible to tag the liquibase images on Docker by liquibase version? This is so that we can pull only a specific liquibase version.

Thanks!

**Comment by raphaelstolt** [comment]
Yes, please apply this helpful practice.

**Comment by frodonLD** [comment]
Hi, 

What about this one plz? This can be really helpful :/

Thanks

**Comment by r2liquibase** [comment]
Check out what we've done. for 3.10.x and latest. Thanks!

**Comment by devopsix** [comment]
That's definitely very helpful!

May I suggest providing tags like “3”, “3.10” and “3.10.1”?

IMHO that's a common tagging convention for projects using numeric versioning. Having such tags, users would have the freedom to pin to `major`, `major.minor` or even `major.minor.patch`. In my projects I would use `major` whereas I would state `major.minor.patch` in a docker-compose.yml file I might include as an example with a bug report.

Some examples:

- [alpine](https://hub.docker.com/_/alpine?tab=tags&page=1&name=3)
- [docker](https://hub.docker.com/_/docker?tab=tags&page=1&name=19)
- [mysql](https://hub.docker.com/_/mysql?tab=tags&page=1&name=8)

**Comment by r2liquibase** [comment]
Hey @devopsix . We're on this today. Thanks for the advice!
