### ISSUE TITLE
New release needed with fix for postgres CVE

### ISSUE THREAD

**Issue by jhancock93** [liquibase/docker#300]
I see there was a new release of liquibase image (v4.27.0) including the fix for a critical CVE is postgres dependency: https://github.com/liquibase/liquibase/releases/tag/v4.27.0. Is there an ETA for a new release of the corresponding docker images? Specifically looking for 4.27-alpine.

**Comment by jnewton03** [comment]
4.27.0 docker image tag was released as well:
https://hub.docker.com/r/liquibase/liquibase/tags
