### ISSUE TITLE
3.10.x build on dockerhub is broken

### ISSUE THREAD

**Issue by DmitryMaletin** [liquibase/docker#33]
when I run latest / 3.10.x image from dockerhub it's failed with error: 
```
starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.
```

**Comment by ofim26** [comment]
I have the same error (latest / 3.10.x):
`Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.`

**Comment by alkoclick** [comment]
For those who are coming here with failed builds: `--entrypoint /liquibase/liquibase`

For the library maintainers: The `docker-entrypoint.sh` (in `/usr/local/bin/docker-entrypoint.sh`) file is not executable. Even when it is, please make sure that the liquibase user has permissions to run it, becomes it's currently owned by root

**Comment by r2liquibase** [comment]
Thank! We're reviewing the PR from @rk13.

**Comment by r2liquibase** [comment]
Looks like the issue is resolved. Please let us know if you continue to have issues. Thansks!
