### ISSUE TITLE
Can I config my liquibase.properties with envionment variables

### ISSUE THREAD

**Issue by dazuimao1990** [liquibase/docker#36]
Hello，I'm learning to use Liquibase with docker.

Can I config my liquibase.properties with envionment variables which define by myself？

For example.

```bash
url=jdbc:mysql://${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-test}

# Enter the username for your Target database.
username: ${MYSQL_USER}

# Enter the password for your Target database.
password: ${MYSQL_PASSWORD}
```

If it can be supported, I can use the following command:

```bash
docker run -ti -v $(pwd)/changelog:/liquibase/changelog -e MYSQL_HOST=<somewhere> -e MYSQL_PORT=<someport> -e MYSQL_USER=<myuser> -e MYSQL_PASSWORD=<Whoknows> --name=liqui --rm liquibase:tag update
```

Perhaps this is a good use for the K8s environment.

**Comment by r2liquibase** [comment]
Hi, @dazuimao1990 . Regarding 1428, this is the feature request to cover this: https://github.com/liquibase/liquibase/issues/1179.

You can always use environment variables at the command line and use things li

`docker run -ti -v $(pwd)/changelog:/liquibase/changelog -e MYSQL_HOST=<somewhere> -e MYSQL_PORT=<someport> -e MYSQL_USER=<myuser> -e MYSQL_PASSWORD=<Whoknows> --name=liqui --rm liquibase:tag --url="jdbc:mysql://${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-test}"  update`

More options are available here: https://docs.liquibase.com/workflows/database-setup-tutorials/mysql.html

Does that help?

**Comment by dazuimao1990** [comment]
> Hi, @dazuimao1990 . Regarding 1428, this is the feature request to cover this: [liquibase/liquibase#1179](https://github.com/liquibase/liquibase/issues/1179).
> 
> You can always use environment variables at the command line and use things li
> 
> `docker run -ti -v $(pwd)/changelog:/liquibase/changelog -e MYSQL_HOST=<somewhere> -e MYSQL_PORT=<someport> -e MYSQL_USER=<myuser> -e MYSQL_PASSWORD=<Whoknows> --name=liqui --rm liquibase:tag --url="jdbc:mysql://${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-test}" update`
> 
> More options are available here: https://docs.liquibase.com/workflows/database-setup-tutorials/mysql.html
> 
> Does that help?

Great . Has this feature been implemented?

**Comment by r2liquibase** [comment]
Not yet!

**Comment by nvoxland** [comment]
One work-around would be to create your own custom container `FROM liquibase/liquibase` that replaces `/liquibase/docker-entrypoint.sh` with something like:

```
#!/bin/bash
set -e

for varname in "${!LIQUIBASE_@}"; do
  propName="${varname/LIQUIBASE_/}"
  propName="${propName/_/}"
  propValue="${!varname}"

  printf "${propName}: ${propValue}\n" >> liquibase.properties
done

/liquibase/liquibase "$@"
```

That will collect any `LIQUIBASE_*` environment variables into a liquibase.properties file with the LIQUIBASE_ prefix stripped off. 

That lets you have LIQUIBASE_URL as an environment variable which will be stored in the liquibase.properties file as `URL=` and liquibase will use it.

We did not include it in the standard docker-entrypoint.sh file because that ends up saving the potentially secure values like password to a file in your container. But, if you are OK with that you can set that up locally.

**Comment by r2liquibase** [comment]
Great idea. I'm going to close this so that we can track this via the Liquibase issue.
