### ISSUE TITLE
Documentation error: changeLogFile cannot be found on the mounted /liquibase/changelog folder

### ISSUE THREAD

**Issue by tpzumezawa** [liquibase/docker#47]
I am migrating liquibase execution from a SpringBoot application to a stand alone docker container execution. I wanted to keep the same folder structure that the SB app was using.

On the "Changelog Files" section it is specified that:
"Your --changeLogFile argument should list paths relative to  /liquibase/changelog"
And an example is given.

I tried to run a similar command within my docker-compose project:
  liquibase:
    image: liquibase/liquibase:3.10.3
    command: --url="jdbc:mysql://mysql/focalpoint-dev" --username=focalpoint --password=hola --changeLogFile=db/changelog/db.changelog-master.yaml  update
    volumes:
    - /home/vagrant/src/focalpoint/focalpoint/src/main/resources/:/liquibase/changelog:z

I would get the following error:

"Unexpected error running Liquibase: db/changelog/db.changelog-master.yaml does not exist"

To fix this I would either have to:
- Add the full changelog file path like this: /liquibase/changelog/db/changelog/db.changelog-master.yaml
- Add the "--classpath=/liquibase/changelog" argument to the command (this seems to allow to use relative path instead of the absolutepath).

Maybe this should be mentioned on the Changelog Files section and examples.

**Comment by r2liquibase** [comment]
@szandany would you mind taking a look at this one? thanks!

**Comment by szandany** [comment]
Hi @tpzumezawa,

It looks like you are trying to map your changelog path from your **resources** folder to the /liquibase/**changelog** docker container file path.

You can probably just reference the rest of the path in the **--changeLogFile** flag with a **relative path**.
Since the Liquibase command is already running from the **/liquibase** folder, you would just need to specify the **changelog** folder as your relative path as a starting point.

For example:
`command: --url="jdbc:mysql://mysql/focalpoint-dev" --username=focalpoint --password=hola --changeLogFile=**changelog**/db/changelog/db.changelog-master.yaml update`

Please let me know if that worked out for you and if you have any questions.

**Comment by szandany** [comment]
Hi @tpzumezawa,

Please disregard my previous comment as it would be just a workaround.
It appears that we had a bug in image `3.10.3` that is now resolved in `latest` image (currently 4.2.2).
Please try to change your liquibase-docker image to `latest` and you should be ok with your original setup.

Here is how I tested this:
`$ docker run --rm -v /Users/support.liquibase.net/CLI-Projects/H2/resources:/liquibase/changelog liquibase/liquibase:3.10.3 --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=db/changelog/db.changelog-master.yaml --username=admin --password=password status --verbose
Liquibase Community 3.10.3 by Datical
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Get advanced features and support at          ##
##      liquibase.com/protrial                    ##
##                                                ##
####################################################
Starting Liquibase at Mon, 01 Feb 2021 22:42:54 UTC (version 3.10.3 #32 built at Mon Oct 12 07:24:42 UTC 2020)
Unexpected error running Liquibase: db/changelog/db.changelog-master.yaml does not exist
For more information, please use the --logLevel flag
support.liquibase.net:~/CLI-Projects/H2

$ docker run --rm -v /Users/support.liquibase.net/CLI-Projects/H2/resources:/liquibase/changelog liquibase/liquibase:latest --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=db/changelog/db.changelog-master.yaml --username=admin --password=password status --verbose
Liquibase Community 4.2.2 by Datical
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 22:43:02 (version 4.2.2 #36 built at 2020-12-09 20:07+0000)
1 change sets have not been applied to ADMIN@jdbc:h2:mem:liquibase_dev
     db/changelog/db.changelog-master.yaml::1612218552998-1::support.liquibase.net (generated)
Liquibase command 'status' was executed successfully.`

**Comment by damiandoan** [comment]
> Hi @tpzumezawa,
> 
> It looks like you are trying to map your changelog path from your **resources** folder to the /liquibase/**changelog** docker container file path.
> 
> You can probably just reference the rest of the path in the **--changeLogFile** flag with a **relative path**. Since the Liquibase command is already running from the **/liquibase** folder, you would just need to specify the **changelog** folder as your relative path as a starting point.
> 
> For example: `command: --url="jdbc:mysql://mysql/focalpoint-dev" --username=focalpoint --password=hola --changeLogFile=changelog/db/changelog/db.changelog-master.yaml update`
> 
> Please let me know if that worked out for you and if you have any questions.

Thank you! That is correct.

**Comment by adjenks** [comment]
I couldn't get it to work for the life of me without using `--classpath=/liquibase/changelog`

**Comment by BondAnthony** [comment]
@adjenks I agree you need to add the classpath parameter for this to work.
