### ISSUE TITLE
custom extension not detected by docker image

### ISSUE THREAD

**Issue by imod** [liquibase/docker#48]
I'm trying to use a custom extension we made with the docker image.

The extension (`CreateTableGeneratorMySqlRowFormatDynamic`) modifies each `CREATE TABLE`- statement to add `ROW_FORMAT=DYNAMIC` to it (for MySQL 5.6). (https://gist.github.com/imod/49ecf35fcf783e44fa031cb5bb27573e)

I package it in to a jar and add the jar to the classpath:

```
docker run --rm -v /Users/domi/work/ws/xxx/persistence/target/liquibase:/liquibase/classpath \
-v /Users/domi/work/ws/yoo/persistence/src/main/resources/mydb/db/:/liquibase/changelog/ \
liquibase/liquibase:3.10.x \
--url="$DB_URL" \
--changeLogFile=/liquibase/changelog/db.changelog-master.xml \
--username="$DB_USERNAME" \
--password="$DB_PASSWORD" \
--logLevel=debug \
--classpath=/liquibase/changelog:/liquibase/classpath/mytools.jar \
update
```

To check if this all works fine, I have `changeSet` which verifies the correctness for each liquibase run:

```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.3.xsd"
	logicalFilePath="db.changelog-init_default_settings.xml">

	<changeSet id="drop foo table if exists" author="Dominik Bartholdi" runAlways="true" dbms="mysql,mariadb">
		<preConditions onFail="CONTINUE">
			<tableExists tableName="foo" />
		</preConditions>
		<comment>make sure we always create a new table to do a check on it</comment>
		<dropTable tableName="foo" />
	</changeSet>

	<changeSet id="create foo table" author="Dominik Bartholdi" runAlways="true" dbms="mysql,mariadb">
		<comment>this creates a dummy table we only use to check if tables get created with the correct ROW_FORMAT</comment>
		<createTable tableName="foo">
			<column name="dummy" type="VARCHAR(10)" />
		</createTable>
	</changeSet>

	<changeSet id="check foo for correct row_format" author="Dominik Bartholdi" dbms="mysql,mariadb" runAlways="true">
		<preConditions onFail="HALT">
			<sqlCheck expectedResult="DYNAMIC">SELECT UPPER(ROW_FORMAT) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'foo' AND TABLE_SCHEMA=DATABASE();</sqlCheck>
		</preConditions>
		<comment>because we rely on the tables being created with the correct ROW_FORMAT per default, we must check for this at every run!</comment>
		<dropTable tableName="foo" />
	</changeSet>

</databaseChangeLog>
``` 

Now, because the extension does not get applied, i get this error:

```
10:44:55.509 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: Preconditions Failed
liquibase.exception.MigrationFailedException: Migration failed for change set mydb/db/changelog/db.changelog-init_default_settings.xml::check foo for correct row_format::Dominik Bartholdi:
     Reason: 
          /liquibase/changelog/db.changelog-master.xml : SQL Precondition failed.  Expected 'DYNAMIC' got 'COMPACT'
```

When I run liquibase with `debug`, then I do see that the extension jar gets added to the classpath:

```
Starting Liquibase at Tue, 01 Dec 2020 11:09:06 UTC (version 3.10.3 #32 built at Mon Oct 12 07:24:42 UTC 2020)
11:09:06.510 DEBUG [liquibase.integration.commandline.Main]: Adding 'file:/liquibase/changelog/' to the Java classpath.
11:09:06.512 DEBUG [liquibase.integration.commandline.Main]: Adding 'file:/liquibase/classpath/mytools.jar' to the Java classpath.
11:09:06.534 DEBUG [liquibase.servicelocator.ServiceLocator]: ServiceLocator.findClasses for liquibase.database.Database
```

But I do not see this output, which I see when I run the changeset with the maven plugin:

`[DEBUG] liquibase.sqlgenerator.ext.copy.CreateTableGeneratorMySqlRowFormatDynamic matches liquibase.sqlgenerator.SqlGenerator`

The full log can be found here: https://gist.github.com/imod/49ecf35fcf783e44fa031cb5bb27573e#file-debug-log

Just to confirm: this all works when I run it with the liquibase maven plugin (https://docs.liquibase.com/tools-integrations/maven/commands/maven-update.html) - but we need be able to execute the changesets without maven and therefore wanna use docker.

**Comment by imod** [comment]
I did some more testing and it is working when I place the extension jar in the same location where all other jars of the liquibase distribution are: `/liquibase/lib/`.
Therefore I created my own Docker image with this `Dockerfile`:

```
FROM liquibase/liquibase:3.10.x

COPY --chown=liquibase:liquibase target/mytools.jar /liquibase/lib/mytools.jar
COPY --chown=liquibase:liquibase src/main/resources/db /liquibase/changelog
```

This eases the whole execution too:

`docker run --rm myliquibase:latest --url="$DB_URL" --changeLogFile=/liquibase/changelog/db.changelog-master.xml --username="$DB_USERNAME" --password="$DB_PASSWORD" --logLevel=info update`

But I don't know why it does not work with the `--classpath` option.

**Comment by r2liquibase** [comment]
Glad you found a happy path for that extension. We'll see about making extensions easier to include in the Docker image. Thanks!

**Comment by r2liquibase** [comment]
@imod What do you think of this approach? We're thinking of having seperate images that inherit the Liquibase base image and add the extension they would like to use. This avoids having all the extensions in an image to combat bloat.

**Comment by imod** [comment]
@r2liquibase do you mean in the same way as I described in my comment https://github.com/liquibase/docker/issues/48#issuecomment-736556166 ?

That means you don't have to change anything on your site - correct?

**Comment by r2liquibase** [comment]
I'm an idiot. Forgot to put in the link to the PR: https://github.com/liquibase/docker/pull/64. Ha!

**Comment by imod** [comment]
:) ...so you will provide some dedicated images for well known extensions? 
I think that's a good idea - but it will not help in the case I described, where I have a custom extension (build by myself). But thinking about the whole setup, I would not want it to be different for my own extension too - the setup as I use now (described above) is basically the same as you would do with the well known extensions and I think this is the most simple way. 
Calling the image is very simple and easily understood. 

👍

**Comment by r2liquibase** [comment]
In the meantime, you can copy the Dockerfile in the PR and just roll your own knowing that we'll always keep the parent Docker image updated.

**Comment by r2liquibase** [comment]
Hi, @imod. You good?
