### ISSUE TITLE
Some packages are not available due to strange line in dockerfile

### ISSUE THREAD

**Issue by LoneEngineer** [liquibase/docker#5]
Hi,

I don't know is it expected or not (and that goal you tried to achieve), but adding
`rm -rf /var/*/apt/*`
into your Dockerfile prevents installing additional packages (e.g. netcat-openbsd) when someone is trying to extend you functionality. E.g. netcat is required if you want to use 'wait-for' functionality (waiting until database container will be ready to serve connections) inside docker-compose.

**Comment by r2liquibase** [comment]
Roger that @LoneEngineer . I think this is resolved. That line is no longer in the Dockerfile.
