### ISSUE TITLE
Publish docker image for v4.3.2

### ISSUE THREAD

**Issue by Constantin07** [liquibase/docker#55]
Hi,

Is there any chance to publish docker image for release v4.3.2 ?

Thanks

**Comment by r2liquibase** [comment]
Just pushed it yesterday @Constantin07 ! How does it look?

**Comment by Constantin07** [comment]
> Just pushed it yesterday @Constantin07 ! How does it look?

Thanks @r2liquibase , already pulled it and ran - all is works fine.

**Comment by r2liquibase** [comment]
DOPE! Thanks for the quick feedback!
