### ISSUE TITLE
Examples have incorrect path to mounted files

### ISSUE THREAD

**Issue by robert-close** [liquibase/docker#87]
When running the commands on my Ubuntu machine and mounting the path as described, --changelogFile="/liquibase/changelog/changelog-master.yml" is not found. The reason is that the initial PWD when I exec into the container is /liquibase already. 

I used --changelogFile="changelog/changelog-master.yml" to correct the issue.

**Comment by r2liquibase** [comment]
Understood. Sounds like you have a resolution for this. Are you OK?

**Comment by robert-close** [comment]
Yes. PRs incoming!

**Comment by r2liquibase** [comment]
Thanks! Make sure to sign up for Liquibase Legends to get sweet swag!!! https://www.liquibase.org/community/liquibase-legends

**Comment by jandroav** [comment]
Hi @robert-close 

As shown here https://github.com/liquibase/docker#changelog-file-example, `--changelogFile=changelog/` is the expected path.
