### ISSUE TITLE
add tag 3

### ISSUE THREAD

**Issue by xenoterracide** [liquibase/docker#9]
should be possible to do `liquibase/liquibase:3` so that when 4 hits we aren't automatically upgraded, in theory there should also be a `3.8` and a `3.8.9` etc, but I mostly care about that major version.

**Comment by devopsix** [comment]
Might be a duplicate of #3.

But tagging images is a must-have IMHO.

**Comment by xenoterracide** [comment]
yeah looks like a duplicate, this is just a subset
